{% set version = "1.22" %}
{% set name = "cliquer" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/dimpase/autocliquer/archive/v{{ version }}.tar.gz
  sha256: 7011ebf3243e81e4eb8259cd75873a2bcdb0faa66fe50d4e7582ce505a66a7ce

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - automake
    - libtool
    - make
    - {{ compiler('c') }}
  host:

test:
  commands:
    - test -f ${PREFIX}/include/{{ name }}/{{ name }}.h
    - test -f ${PREFIX}/lib/lib{{ name }}.dylib  # [osx]
    - test -f ${PREFIX}/lib/lib{{ name }}.so     # [linux]

about:
  home: https://users.aalto.fi/~pat/cliquer.html
  license: GPLv2+
  license_file: LICENSE
  summary: Cliquer is a set of C routines for finding cliques in an arbitrary weighted graph

extra:
  recipe-maintainers:
    - isuruf
