travis:
  secure:
    BINSTAR_TOKEN: mKvHDqCDXD9zFXHTe+WceMqdT9qoprxSpkykv0sh7CsVsEiWlHFEBI6AIy9GqZvLbF6Qzvu2jFLoPoMsq34m2mkBcDZjnHxqxOpNgYmP4pVHy7LIiO6IeTBTgfEIy8hPxhjYvmxwbRC9hAbyVJQ1JetTwa9ZXvi7wcOEc3pQqHDBoIpeS9WGg8TEUTCPANpuXnf8d7zQwV3qu5YkaFFysY9vBe4h1InIayFQO4Dt1IMKBx7EJaPN9Ma1lmzyIGA8PRLI6OwMwosRl3qBzADJ8g/kZtQs8z1A5wJtTOclU7zzUYvWWsBiN8kD5jqNGlYQC2TYntPOZ/ii3CqOnKpjWxDfSSFCFtRHrqbWlOT9jYIaUOuSVQw8k20paN6QdzoZDJ1MR+/IzsTaS7WjC8XFbFO7qTyAtddkrWXabzrLhMBRXQ/REVsHqMyiV7zrCVAnynghzR4gECuDHVhE9r+D/MvJjltW+3TSHl/tmwXhJzQ6RR1dPv4pcf59vAd6EAIAg4vbqSmCVDTxwf8McpR3H7rDd2UY+P5wsOQtriDNgGIS3RFgaRlQMRRfgTddiWMc7ZlrJHLkZujddGuUWbEokWc4uBsS5UsyJ9HO6NTs5nYm3yH3vFZG2TeQ17LyonIJgkqedekz9Cp6o9mZAAwE0etiuyIis367hCBTpc2aYBs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
