travis:
  secure:
    BINSTAR_TOKEN: A4Je8kZIaAUnJsu26zUgLn+3H7DuQbAyOMFurRq8PP9+Wyh4Ni8hsWBtnh5NcLeG3MP+2gTHZ+UkHngHDJgD6FVxz/zzvHcX2ktJkHaCOhTMBl1xFRN/bdAeNp6t6C3blS9QAJ3uUBScGG7DhntjlC1N604NOsOalGhyhZ5y99xjJW2RYybIseGRou+kD5Bmip6X9X6FEThyOLR6lMLaZAKTeNvGXLn1Yf5EfMbIWBn2xgEOWYZDit1syHUR4RkJfuhcVqVybTVlgv3WEF239zKgf7wmkKld7GdRtfrs6xEN5RdsVz0JIFaE1NbA0s5MJsqKPE9K20NDIBGrz5LmE6L9Q2i5bzDVHXlARHDG6uhc9wNiAWpVD3coOjZ00fX2WTOp2qpXNEnS84kSIOMcRBc7GoJFM2rpJp76ZMFC5tw6XZy0mhI1T84VXzWRUW36FL/nuBWxI+y+iS5bqzU68lE9Jv421q+1Ay6glmRkqoD3mepysdVNeO2hRwRGJB8t4t2egMGxWYk1V9nv0QWURh54wSrcUpE7LuOAq+FiJSt4DKATonr8ZSQHWw/jEOwyCXSKZI4QMM4OZg1+1oT50iG5dUjAoM0f/3Bp5dPoGAjKCUaGqg5XjBrFgherTQk475nfcZuJhUpKXqK7J4LeH5WwY0rxfqT2zDbXCiqy2aE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
